### PR TITLE
Integrate goframe

### LINKED ISSUE #10: 建议新增对goframe框架的内置支持
在“1.3.3 多服务端框架”建议增加对goframe框架的内置支持

### PR DESCRIPTION
**Pull request by ccb1900**
### Describe what this PR does / why we need it

Integrate goframe

### Does this pull request fix one issue?

Fixes #10 

### Describe how to verify it

example/http/goframe

### Special notes for reviews

I do not know how to test status.go

### CODE REVIEW

**Comment by mlboy** [comment]
please add apache license header

**Comment by ccb1900** [comment]
> please add apache license header

it is ok

**Comment by mlboy** [comment]
hi, could you help me resolve conflicting files?

**Comment by ccb1900** [comment]
> hi, could you help me resolve conflicting files?

done

**Pull request merged**
